import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "@/components/Header";
import { SanityLive } from "@/sanity/lib/live";
import { draftMode } from "next/headers";
import DisableDraftMode from "@/components/DisableDraftMode";
import { VisualEditing } from "next-sanity";
import Footer from "@/components/Footer";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "AuraCart",
  description: "Generated by Muazam Mughal",
};

export default  async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider dynamic>
    <html lang="en">
      <body
      
        className=" bg-gradient-to-r from-stone-100   to-black  text-white opacity-90">

          {(await draftMode() ).isEnabled && (
            <>
            <DisableDraftMode/>
            <VisualEditing/>
            </>
          )}
        <Header/>

        {children}

        <Footer/>

        <SanityLive/>

        
      </body>
    </html>
    
    </ClerkProvider>
  );
}
